User: 测试客户
ServerName: 测试服务
ServerIP: 169.254.111.253
ServerMac: 00-00-00-00-00-00
PushConf:
  DingToken: you dingding token
  DingSecert: you dingding secret
  MailUser: you mail account
  MailKey: you mail password
  Mailaddr: Email notification recipient
  SecCheck: true
  Mailpush: true
Bfilesuffix:
- .php
- .exe
- .php3
MonitorDirs:
- e:\test
ExcludeDirs:
- c:\tx1ee\test
